### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by TimBeyer** [Matt-Esch/virtual-dom#103]
I am trying to transform some of our old views to use `virtual-dom` and the basic infrastructure is in place. I can transform the templates to a `vTree` and then create the corresponding elements etc.

What I've noticed is that HTML entities are not parsed correctly, so `&nbsp;` shows up as exactly that.  
Where do you think the handling for this belongs? When setting `innerText` the things are obviously not decoded, but setting `innerHTML` for all text nodes also seems weird.

Should they maybe be translated to their associated characters when parsing the HTML and transforming them to a `vTree`, even if that means the HTML rendered by the server and the virtual-dom rendered client-side differ? 

I'm not entirely sure which component's responsibility it is to deal with these things.

**Comment by bitinn** [comment]
Sorry to jump an old thread: so what should we use nowadays?

On server-side this works:

```
h('script', 'text': 'var x = "abc"');
```

But client-side we want this?

```
h('script', {
    'text': 'var x = "abc"'
});
```

PS: `text` is not supported by `vdom-to-html`, we will need to work on it if that's the recommended approach.
