### ISSUE TITLE
ClojureScript implementation ?

### ISSUE THREAD

**Issue by siscia** [Matt-Esch/virtual-dom#107]
Hi,

maybe I am wrong, but I could swear about a ClojureScript implementation, however I couldn't find it...

Anybody is aware of such library ?

Sorry, for the question here...

Simone

**Comment by tiye** [comment]
This one? https://github.com/dubiousdavid/dominator

Also got one by myself https://github.com/Respo/respo/tree/master/src/respo/render

**Comment by ashnur** [comment]
https://github.com/exupero/vdom
