### ISSUE TITLE
h(html) ?

### ISSUE THREAD

**Issue by rauchg** [Matt-Esch/virtual-dom#109]
jQuery style node initialization:

```js
h('<p class="woot">', { style: { dynamic: val } })
```

**Comment by blesh** [comment]
For the sake of developer ergonomics, is there any effort already under way to parse some sort of markup into a series of virtual-dom? It could be a useful build step for something like Grunt, Gulp or Brococli.

**Comment by rauchg** [comment]
should be trivial for you to generate it using the rxjs transformer

**Comment by Raynos** [comment]
@blesh https://github.com/Matt-Esch/virtual-dom/wiki#html-to-vdom

**Comment by neonstalwart** [comment]
cleaning up old tickets - open another issue if there's something here which is still not resolved
