### ISSUE TITLE
Attaching DOM events not working

### ISSUE THREAD

**Issue by pm-debjit-biswas** [Matt-Esch/virtual-dom#129]
I am trying to attach DOM events to the rendered nodes but it is not working.

I have used the following syntax:

``` javascript
function render()  {
    return h('div', {
      style: {
        height: "100px",
        width: "100px",
        background: "#CCC"
      },
      "ev-click": function () {alert('hi');},
    }, "Hello World!");
}
```

What am I missing here?

**Comment by AlexGalays** [comment]
Got bitten by this too; Nothing in the virtual-dom documentation indicates that a Delegator is required (or I didn't find it). The indirections between Matt-Esch's and Raynos' repos can be cumbersome. If it's a mercury thing, then it shouldn't be in hyperscript?

For info, I'm going to use the regular [on + event] attributes for simple cases, and [Gator]() for delegated events, if needed (I hope not). It's rather simple and avoid creating tons of hooks.

**Comment by Raynos** [comment]
@AlexGalays it is in `virtual-hyperscript`. Let me update the documentation.

**Comment by staltz** [comment]
Why is the default advice in virtual-dom docs to use `ev-click` and not `onclick`? `ev-click` with dom-delegator seems to be just mercury-specific. Also it creates some coupling between the two libraries, while mercury is about true modularity.

**Comment by Raynos** [comment]
There is no default advice.

The only place its mentioned is in the virtual-hyperscript documentation where it documents it exists.

virtual-dom has no opinions about this matter. You can use all properties and all attributes including `onclick`. You can also use `ev-` in h() to use the EvStore feature.

**Comment by Raynos** [comment]
@staltz 

If you have a novel approach to remove the coupling I would love to hear it.

A virtual scene representation of your UI needs to have some kind of markers for knowing where to dispatch events to. 

For performance reasons these markers are stored in the DOM nodes so we can do an O(1) lookup, this requires hooks. If we can find a decoupled approach I'd love to explore that, as well as explore real benchmarks to see whether we can use a less performant but more decoupled solution.

**Comment by staltz** [comment]
I guess I don't have a novel approach in mind.  One thing comes to mind, which is listening to top-level events on the window (e.g. window.onclick) and building a custom bubbling/catching system. But this is just a tossed idea.

**Comment by neonstalwart** [comment]
@staltz :smile: you just described dom-delegator.  it listens to events on the document and dispatches them to the `'ev-foo'` handlers

**Comment by Raynos** [comment]
@staltz "building a custom bubbling/catching system" is exactly dom-delegator.

The bit that needs decoupling is how to dispatch to the ev-foo handlers without coupling to dom-delegator

What we have done is coupled to `ev-store` ( https://github.com/Raynos/ev-store ) which can then be read from my any bubbling / delegation system.

Matt-Esch might use that to do bubbling / delegation at the "component" boundary instead of at the "global" boundary.
