### ISSUE TITLE
Question about patch generation

### ISSUE THREAD

**Issue by paf31** [Matt-Esch/virtual-dom#153]
I'm fairly new to `virtual-dom`, so please excuse me if this question is inappropriate, but I noticed what I would consider odd behavior while writing [this small demo](http://functorial.com/24-days-of-purescript/rabbit-example/html/). The code (PureScript, sorry) is available [here](https://github.com/paf31/24-days-of-purescript/blob/gh-pages/rabbit-example/src/Main.purs) as well.

The issue is that the computed diff is much larger than I would expect. Instead of simply inserting a new `li` element at the front of the `ul` (which is what I would expect), the changes cascade down through each `li`, resulting in a patch with size linear in the size of the model.

Is this expected? I would understand if it were an artifact of the heuristics applied to get a fast diff, but I just wonder if it would be possible to represent these small changes as smaller patches.

Thanks.

_Edit_: I've updated the demo to log the patch to the console at each step, so that you can see the behavior.

**Comment by paulocheque** [comment]
What happens if two keys are identical?
