### ISSUE TITLE
Passing HTML string as child

### ISSUE THREAD

**Issue by bitinn** [Matt-Esch/virtual-dom#162]
I must be missing something here, but couldn't find it.

Do I have to use https://github.com/Matt-Esch/virtual-dom/wiki#html-to-vdom tools to convert them into VNode first?

Imagine a feed reader displaying feed content, we don't actually need to manipulate feed content itself, just changing the innerHTML of its container is enough. What's inside that container doesn't matter to `virtual-dom`, it can be an immutable blackbox.

Passing HTML as text will be escaped by modules like `virtual-dom-stringify` and `vdom-to-html` (rightly so).

**Comment by neonstalwart** [comment]
nodes have a property called `innerHTML` :wink: 

```js
h('div', { innerHTML: '<span>Hi there</span>' });
```

**Comment by bitinn** [comment]
Ah thx, saw it and missed it. According to #47, innerHTML will be considered a property, and follow the blackbox logic I described above.

I guess it's up to `virtual-dom-stringify` and `vdom-to-html` to do something with innerHTML then? For browser it's handled by DOM, but for node.js, something has to happen for it to render properly.
