### ISSUE TITLE
JSDoc / Closure Compiler annotations

### ISSUE THREAD

**Issue by sayrer** [Matt-Esch/virtual-dom#167]
I just noticed https://github.com/Matt-Esch/virtual-dom/blob/master/docs.jsig

I wish I had seen it earlier. Is there any chance you would take a patch to convert that information to JSDoc and Closure annotations?

**Comment by Matt-Esch** [comment]
No patches for inline documentation will be accepted. Comments should be reserved for special-case annotations only. PRs to improve docs in general are welcome, just not for docs that impact the source.
