### ISSUE TITLE
Question regarding your vision about this projet

### ISSUE THREAD

**Issue by benzen** [Matt-Esch/virtual-dom#182]
I've seen the experimental tag on the README.
And i'm wondering about your vision about this projet.

To you, does it mean that this projet is just a toy and nobody should depend on it.
Or is rather something you take very seriously and you want to discourage people to make hard commitment on this for now, because the api could drastically change in the near futur.

In any case i propose to add a statement about this on the README just to make it clear.

**Comment by Matt-Esch** [comment]
We take the project seriously. There are people using this in production for real apps and deriving real value from it.

A number of edge cases are yet to be explored though. I am still merging pull requests for some issues that to my mind seem to show some immaturity in the module at a level I find unacceptable for a "stable" module.

I would like to encourage people to use virtual-dom for projects they have in mind, but it comes with the caveat that if you use it in a way someone has not explored yet, you may find yourself raising issues and submitting pull requests to fix things.

Aside from that, documentation needs much improvement. I consider documentation a cementing of the interface, so we should expect the documented parts to be relatively stable and anything else to be experimental.

**Comment by neonstalwart** [comment]
cleaning up old tickets - open another issue if there's something here which is still not resolved
