### ISSUE TITLE
contributor guidelines

### ISSUE THREAD

**Issue by neonstalwart** [Matt-Esch/virtual-dom#192]
@Matt-Esch 

in reference to #191, i'd be glad to build a new dist and tag the release, and then let you publish to npm but just not sure what is involved so figured i'd open an issue to add a document to cover it.

**Comment by Raynos** [comment]
@Matt-Esch I recommend adding something like https://github.com/Raynos/mercury/blob/master/CONTRIBUTION.md into the project.

**Comment by Matt-Esch** [comment]
@neonstalwart I will add contribution guidelines. It will generally fall in line with https://github.com/rvagg/node-leveldown/blob/master/CONTRIBUTING.md - which states that declaring formal releases remains the prerogative of the project maintainer, but I am happy to consider you a project maintainer.

**Comment by neonstalwart** [comment]
that's fine - my question is probably mostly about your expectations for the changelog.  i don't think there's anything else that i wasn't sure about.

**Comment by Matt-Esch** [comment]
the release process is 

- update changelog (with any significant details regarding the differences between the previous and new release, you don't have to put in every detail)
- generate the standalone version
- npm version <patch, minor, major>
- git push origin master --tags
- npm publish

**Comment by neonstalwart** [comment]
that covers what i wanted to know - thank you.

**Comment by Raynos** [comment]
@Matt-Esch I encourage you add a paragraph to CONTRIBUTION.md that is exactly that.

**Comment by kuraga** [comment]
Don't you want to update `CHANGELOG` with each commit changes something?

I think [angular](https://github.com/angular/angular.js/commits/master) is the best example of development infrastructure... [CONTRIBUTING.md](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md)
