### ISSUE TITLE
Adding a class depending on some state

### ISSUE THREAD

**Issue by marlun** [Matt-Esch/virtual-dom#196]
I'm very new to virtual-dom and I'm finding it hard to find guides on how to use it. I've got a widget and depending on if this.value is positive or negative I want to add different classes (xxx--negative or xxx--positive) to a specific element. I get the following now

	return h('.entry', [
			h('span.entry__value', this.value),
			h('span.entry__name', this.name)
	]);

So if this.value is positive I want the span that has the class `entry__value` to also have the class `entry__value--positive`. I'm not sure how to write that though.

**Comment by Raynos** [comment]
`h('span', { className: bool ? 'foo' : 'bar' })`

**Comment by marlun** [comment]
Ha! Feel a little bit stupid. However, is it not possible to return what h() returns and use it to add attributes before returning the object? Something like

    var vel = h(...);
    vel.xxx = 'xxx';
    return vel;

**Comment by Zolmeister** [comment]
Yes, [Zorium](https://github.com/Zorium/zorium) does it for hooks: https://github.com/Zorium/zorium/blob/master/src/z.coffee#L67

See [docs for vnode](https://github.com/Matt-Esch/virtual-dom/blob/master/vnode/vnode.js)

**Comment by marlun** [comment]
Thanks. Will consider this one closed!
