### ISSUE TITLE
function reorderChildren in patch-op.js fails in certain cases 

### ISSUE THREAD

**Issue by yiransheng** [Matt-Esch/virtual-dom#198]
See this jsbin:
[http://jsbin.com/hucuca/1/edit?html,js,console,output](http://jsbin.com/hucuca/1/edit?html,js,console,output)

`reorderChildren` function from: [here](https://github.com/Matt-Esch/virtual-dom/blob/86dc068cc4cd04a9b984c9a21cd7aaca53e038e4/vdom/patch-op.js) throws errors for certain edge cases. For example, in the jsbin link above, when calling `reorderChildren` on a DOM node with 43 childNodes (all DIVs), with new ordering: `[41, 3, 34, 36, 1, 40, 39, 7, 37, 14, 23, 26, 15, 6, 25, 24, 19, 8, 9, 22, 29, 27, 38, 35, 11, 20, 33, 31, 17, 32, 4, 28, 12, 2, 10, 0, 42, 21, 5, 16, 30, 18, 13]` (easily verified as a permutation of [0, 1, 2, ... 42]),  this error gets thrown:

```
TypeError: Cannot use 'in' operator to search for '0' in undefined
```

The result DOM node is not fully reordered according to input/patch, this error happens rarely, but will accumulate overtime, and cause real DOM and virtual-dom to be out of sync. 

EDIT: Ubuntu 14.04 Chrome Version 40.0.2214.115 (64-bit)

**Comment by Matt-Esch** [comment]
This should be fixed in v2.0.0 - reopen the issue if not
