### ISSUE TITLE
Explenation of a Widget (and thunk?)

### ISSUE THREAD

**Issue by marlun** [Matt-Esch/virtual-dom#201]
The README do not mention anything about Widgets but it's obvious from issues and source-code that Widgets is a considerable part of virtual-dom. I would really appreciate an up to date explenation of Widgets in the README (or somewhere else?). Having it in the README would probably keep it up to date since it would be read by a lot of people.

I've also seen the word thunk being used and it's not quite clear to me what that is either?

Thanks!

**Comment by staltz** [comment]
https://github.com/Raynos/mercury/blob/master/docs/widgets.md

**Comment by neonstalwart** [comment]
also, see #183 which is a PR to add docs around all of these concepts.

**Comment by marlun** [comment]
Thanks both of you, will read it all :smile:
