### ISSUE TITLE
hyperscript properties.style is broken

### ISSUE THREAD

**Issue by ArtskydJ** [Matt-Esch/virtual-dom#204]
Bug replication here: http://requirebin.com/?gist=9680589548483ea292fb

```js
var h = require('virtual-dom/h')
var createElement = require('virtual-dom/create-element')

var tree = h('div', { style: 'color: red;' }, [
  h('h1', 'not red')
])
var el = createElement( tree )
document.body.appendChild( el )
```

Using browserify...

**Comment by Zolmeister** [comment]
workaround:

```js
h('div', {
  style: {
    color: 'red'
  }
})
```

**Comment by ArtskydJ** [comment]
Thanks @Zolmeister!

**Comment by littleloops** [comment]
This isn't a bug, it's expected behavior - see https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#propertiesstyle-vs-propertiesattributesstyle

**Comment by ArtskydJ** [comment]
Thanks @littleloops!

**Comment by rstacruz** [comment]
Will this be changed? It seems inconsistent with `className` behavior, where it can accept strings or objects just fine:

```js
h('div', { className: 'box' })
h('div', { className: { box: true, active: false } })
```

**Comment by Zolmeister** [comment]
@rstacruz I couldn't reproduce the object behavior. Could you post a fiddle that uses it?

**Comment by rstacruz** [comment]
oops.. haha.. i guess not.
