### ISSUE TITLE
Cannot add/modify data-* attributes 

### ISSUE THREAD

**Issue by cmtt** [Matt-Esch/virtual-dom#208]
I would like to add data-attributes to nodes generates using the virtual-hyperscript implementation in virtual-dom, but apparently, it doesn't update the DOM accordingly.

A demonstration can be found on http://requirebin.com/?gist=4d7ec4e95855118d57c6 , I expected the button to have an "data-val" attribute set to "0" or the current counter after a click. 

After reading the virtual-hyperscript README, it tells that one could read data-* attributes using the data-set module, but I couldn't find any reference to that in virtual-dom:

> data-*
> 
> If you call h with h('div', { data-foo: "bar" }) it will set data-foo to be a VHook that set's a DataSet property named foo with the value "bar" on the actual dom element.

>It will not set a property data-foo on the dom element.

> This means that somewhere else in your code you can use DataSet(elem).foo to read this property.

"data-val" is an included key in the properties hashmap and set to "0" initially.

**Comment by TimBeyer** [comment]
Try using `dataset` and passing an object like `{ val: 0 }`.

**Comment by cmtt** [comment]
Thanks a lot!

**Comment by neonstalwart** [comment]
...and if you want it to work in browsers that don't support dataset

```js
h('div', { attributes: { 'data-foo': 'bar' } });
```

attributes are not properties - see https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#propertiesattributes

**Comment by neonstalwart** [comment]
see also https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#custom-attributes-data-
