### ISSUE TITLE
Rowspan attribute not working

### ISSUE THREAD

**Issue by mtmacdonald** [Matt-Esch/virtual-dom#232]
I need to create a table with a `rowspan`, like this ([jsfiddle][2]):

    <a href="google.co.uk">Link</a>
    <table>
        <tr>
            <td rowspan=2>Foo</td>
            <td>Baz</td>
            <td>Baz</td>
        </tr>
        <tr>
            <td>Baz</td>
            <td>Baz</td>
        </tr>    
    </table>

But when I try it with virtual-dom, the `rowspan` attribute is ignored ([requirebin][3]):

    var h = require('virtual-dom/h');
    var createElement = require('virtual-dom/create-element');

    function draw()  {
        return h('div', [
          h('a', {href: 'google.co.uk'}, 'link'),
          h('table', [
                h('tr', [
                    h('td', {rowspan: '2'}, 'Foo'),
                    h('td', 'Baz'),
                    h('td', 'Baz')
                ]),
                h('tr', [
                    h('td', 'Baz'),
                    h('td', 'Baz')
                ]),
            ]),
        ])
    }

    var tree = draw();              
    var rootNode = createElement(tree);
    document.body.appendChild(rootNode);

I notice the `href` attribute for the link works as expected, but the  `rowspan` attribute on the  `td` does not.

Why does the rowspan attribute not work?

  [1]: https://github.com/Matt-Esch/virtual-dom
  [2]: http://jsfiddle.net/Le5gyzxy/
  [3]: http://requirebin.com/?gist=23f88375e868910409a1

**Comment by mtmacdonald** [comment]
This [stackoverflow question](http://stackoverflow.com/questions/29774686) solved the issue ("**virtual-dom deals in JavaScript DOM properties, not HTML attributes**").

I'll leave the ticket open because it would help to have this explained in the documentation.

**Comment by neonstalwart** [comment]
@mtmacdonald https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#properties
