### ISSUE TITLE
using inbrowser

### ISSUE THREAD

**Issue by rickdog** [Matt-Esch/virtual-dom#235]
Could you look at http://stackoverflow.com/questions/29888878/how-do-you-use-virtual-dom-gist-in-browser to see my question about using this outside of nodeJS?  I'm trying to use virtual-dom straight from the browser.

**Comment by hallgren** [comment]
Run it through browsify.

**Comment by Zolmeister** [comment]
Or webpack

**Comment by neonstalwart** [comment]
cleaning up old tickets - comment here or open another issue if there's something here which is still not resolved
