### ISSUE TITLE
Attach real DOM to a VTree?

### ISSUE THREAD

**Issue by tomekwi** [Matt-Esch/virtual-dom#240]
Hi,

is it possible to construct a DOM tree outside *virtual-dom* and attach it as a child to a `VirtualTree`?

Here’s some reasoning behind this: <https://github.com/lhorie/mithril.js/issues/326#issue-47569726>.

Here’s a solution I came up with for Mithril: <https://github.com/tomekwi/mithril-n>.

**Comment by tomekwi** [comment]
Oh, and here’s some benchmarks: <http://jsperf.com/rendering-dom-in-mithril/2>.

**Comment by Zolmeister** [comment]
see https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md

**Comment by tomekwi** [comment]
Thanks for the heads up! Looks interesting :)
