### ISSUE TITLE
Example of using SVG on a page?

### ISSUE THREAD

**Issue by eightyeight** [Matt-Esch/virtual-dom#255]
I've been trying to get SVG elements working. While I can construct SVG DOM elements with regular calls to `virtual-hyperscript`, the elements don't appear to be rendered correctly. I assume I'm supposed to use the `svg` submodule, but trying a simple hello-world with `mercury`:

````javascript
var document = require('global/document');
var hg = require('mercury');
var h = hg.h;
var s = require('virtual-dom/virtual-hyperscript/svg');

function App() {
	return hg.state({});
}

App.render = function render(state) {
	return h('div', [
		s('svg', {width: 100, height: 100}),
		'Hello world'
	]);
};

hg.app(document.body, App(), App.render);
```

Errors with the following:

```
Uncaught Error: Unexpected virtual child passed to h().
Expected a VNode / Vthunk / VWidget / string but:
got:
{
    "tagName": "svg",
    "properties": {
        "attributes": {
            "width": 100,
            "height": 100
        }
    },
    "children": [],
    "namespace": "http://www.w3.org/2000/svg",
    "count": 0,
    "hasWidgets": false,
    "hasThunks": false,
    "descendantHooks": false
}.
The parent vnode is:
{
    "tagName": "DIV",
    "properties": {}
}
```

**Comment by Raynos** [comment]
Have you tried hg.svg ?

**Comment by Raynos** [comment]
Oh wait; I removed svg. The issue is two copies of virtual Dom

Mercury probably uses 1.0 and your probably using 2.0

**Comment by eightyeight** [comment]
Oh. That appears to be the case. I didn't try a pure example without `hg` in the loop - didn't even cross my mind that I was using two different versions. Gotta get used to npm. I'll see if using the correct version lets me do it.
