### ISSUE TITLE
In what particular use-cases would we need additional xss filter?

### ISSUE THREAD

**Issue by bitinn** [Matt-Esch/virtual-dom#259]
I am used to running xss filter on all user input before letting them render by templates, but then I realize `VText` is created in real dom with `createTextNode`, which auto encode content, so in many case, we should pass decoded content to `h`.

How about other scenarios, such as attributes? Is XSS filter needed at all?

See related-discussion on https://github.com/yahoo/xss-filters/issues/24 as well.

**Comment by neonstalwart** [comment]
if you use the `innerHTML` property rather than a `VText` node you definitely need to sanitize the input but as far as i'm aware everything else is safe to use without escaping user input.  i take no responsibility though - please confirm for yourself.

**Comment by bitinn** [comment]
There are some edgecase with `href` when dealing url protocol, so as least url are worth sanitizing.

There is no guarantee on `style` or `onXXX` will be safe, but it's easier to just not use them.
