### ISSUE TITLE
Wrong DOM svg

### ISSUE THREAD

**Issue by Tuch** [Matt-Esch/virtual-dom#260]
Hello, 
i have example:
http://requirebin.com/?gist=6fab8e82aee016f2a3e2

Can u help me. I need correct svg element like innerHTML

**Comment by Matt-Esch** [comment]
fromHTML is buggy: it's putting the svg attributes on a properties key, which is not how svg works. It needs to be fixed to put SVG attrbutes on the node.attrbutes object instead of on properties.

**Comment by Tuch** [comment]
You mean something like this?
http://requirebin.com/?gist=3f0c035d19cc4535209d

**Comment by Tuch** [comment]
@Matt-Esch, is actual problem :( I fixed it in our project simply by adding a few lines such as those below:
```
var svgTags = {...}
var svgAttrs = {...};

function applyProperties(node, props, previous) {
....
        } else {
            if (isObject(propValue)) {
                patchObject(node, props, previous, propName, propValue);
            } else {
                if (svgTags[node.tagName.replace('-','').toUpperCase()] && svgAttrs[propName.replace('-','').toUpperCase()]) {
                    node.setAttribute(propName, propValue);
                } else {
                    node[propName] = propValue;
                }
            }
        }
    }
}

```

But it incorrect solution for global case, yes? or not?

**Comment by marcelklehr** [comment]
You could also use http://github.com/marcelklehr/vdom-virtualize

**Comment by Tuch** [comment]
@marcelklehr, Yes. But http://github.com/marcelklehr/vdom-virtualize ignore SVG properties :(

**Comment by marcelklehr** [comment]
Yes, virtualize had problems handling attributes, but that is fixed now. I'm pretty sure it works, would you mind checking again? (Also, please do feel free to file an issue if you encounter such a bug :) )

**Comment by Tuch** [comment]
@marcelklehr, oh!! Thank you very much!

**Comment by marcelklehr** [comment]
Glad I could help ;)
