### ISSUE TITLE
diff-algorithm generates patch with null-node - patch cannot handle null-nodes

### ISSUE THREAD

**Issue by pwde** [Matt-Esch/virtual-dom#268]
Hello,

first: thanks for virtual-dom.

I run into an strange issue in v2.0.0 with keyed rows in a table - I think it is a bug:
* In some cases diff() generates a patch with a null
```javascript
    var patch = virtualDom.diff(vdomOld, vdom);
```
![](http://fs1.directupload.net/images/150611/8u98bev5.png)

* applying the patch generates an error:
```javascript
    domNode = virtualDom.patch(domNode, patch);
```
![](http://fs2.directupload.net/images/150611/6febltw8.png)

I hope, it can be fixed.

Regards,
Peter.

**Comment by neonstalwart** [comment]
can you provide us with a test case that will consistently reproduce this? working from screenshots isn't really going to help us since we probably need to know how the `null` got there to begin with and seeing that it's there doesn't help us know *how* it got there.

**Comment by pwde** [comment]
OK, I'll try to extract a simple test-case... from a complex vdom-tree...

**Comment by pwde** [comment]
Oh, I found a bug in my code... sorry... a key was used twice.
