### ISSUE TITLE
Accept iterable as children

### ISSUE THREAD

**Issue by OliverJAsh** [Matt-Esch/virtual-dom#276]
This would allow such things as `h('div', Immutable.Map(['foo', 'bar']))`, where `Immutable.Map` returns an ES6 iterable.

**Comment by Matt-Esch** [comment]
No plan to add support for ES6 primitives at this stage. The code is stilll ES3 compliant, sorry ;)

**Comment by theefer** [comment]
Added a suggested PR to add support https://github.com/Matt-Esch/virtual-dom/pull/400
