### ISSUE TITLE
pull out hyperscript

### ISSUE THREAD

**Issue by stevenvachon** [Matt-Esch/virtual-dom#281]
in favour of a simple object syntax like [cito.js](https://github.com/joelrich/citojs)

**Comment by Matt-Esch** [comment]
hyperscript isn't a hard dependency if you use virtual-dom, it's just a reasonable default. Creating VNodes comes with various pitfalls as consistency checking.

I'm not going to support replacing this, it's just a reference implementation and I encourage people to write their own functions, using h as a guideline for what could to be corrected.
