### ISSUE TITLE
What does patch() return?

### ISSUE THREAD

**Issue by bitinn** [Matt-Esch/virtual-dom#284]
A strange question, I know, as it's pretty apparent it returns the node after patch.

My question is why do we need `rootNode = patch(rootNode, patches)` ?

I sort of imagine rootNode to be a reference, if we are simply patching its child elements, why would we need to update the reference to rootNode? why isn't rootNode pointing to the *current* dom?

PS: I ran into this silly problem when I find myself not able to patch properly due to only writing `patch(rootNode, patches)` in my renderer.

**Comment by Matt-Esch** [comment]
You only need to care about updating the rootNode if your rootNode changes type. Hopefully you are only updating child nodes most of the time, but it's perfectly legitimate to mutate the root node to a different type of node. Patch is stateless and requires you to pass in the root node. It cannot mutate any location you store that root node. It also can't replace the root node if it's not in the DOM, so it is returned to you.

If you think that you're only updating child nodes, pay attention to the patches list. If you have an example that improperly replaces the root node create an issue with an example of the bug. I don't recall if case sensitivity is an issue, it will depend if you are using `h` or not. `div` patching `DIV` will result in a patch of the node unless you pass it though some case conversion logic, which I think we have in `h`.

**Comment by bitinn** [comment]
Thx for the explanation! I made some assumptions and did some debugging, can someone confirm my understanding is true?

- Each VPatch generated by `diff` contains a `patch` property, I assume it contains the new VNode.

- My initial vdom is from my [vdom-parser](https://github.com/bitinn/vdom-parser) module (a html to vdom module, since we do server-side rendering), I then diff/patch it against the one generated from client-side vdom renderer. I find my root node in the `patches['0'].patch` (and it's the only VPatch), I believe that's why `rootNode = patch(rootNode, patches)` is needed in my case.

- But I failed to observe any type change on root node in my case, both of `patches['0'].patch` and `patches['a']` are VNode, ie. type 2. The main changes I see includes:

    1. vdom from my parser contains `namespace: "http://www.w3.org/1999/xhtml"`, and has `descendantHooks: false` as it doesn't add hooks, whereas vdom from renderer has `namespace: null` and `descendantHooks: true`.
    2. due to way whitespace between tags are treated in browser, vdom from my parser contains a lot more VText node, mostly are newlines and indents (we format html on output). That includes direct children under my root node, but I believe it shouldn't require my root node neither.

- So I am not quite sure where it went wrong.

- As a test, I also did a normal diff/patch between 2 client-side rendered vdom, and I find multiple VPatch on my svg icons (using `xlink:href` attributes) and buttons (using `ev-*` attributes), event though they haven't changed, I assume it's because they are using `Hooks`.

Lastly, a screenshot of my `patches` object for reference:

![screen shot 2015-07-10 at 6 10 37 pm](https://cloud.githubusercontent.com/assets/1484279/8616603/4e564222-272f-11e5-8baf-7d97970db475.png)

**Comment by DeTeam** [comment]
@bitinn 

> Each VPatch generated by diff contains a patch property, I assume it contains the new VNode.

Seem so, and `.vNode` contains the old VNode.

> I find my root node in the `patches['0'].patch`

`0` here indicates, that patching must be performed on the root node.

In your case root node is patched because of the namespace. At the moment in master, key, tagName & namespace should match to not have this node replacement and get property mapping instead.

**Comment by bitinn** [comment]
That explains a lot, thx @DeTeam. I should have looked at the source myself.

https://github.com/Matt-Esch/virtual-dom/blob/master/vtree/diff.js#L43-L45

It also mean I have made an mistake assuming VNode contains the default namespace `http://www.w3.org/1999/xhtml`, while the default namespace is `null`...
