### ISSUE TITLE
Question: How to handle arbitrary attributes?

### ISSUE THREAD

**Issue by Mictian** [Matt-Esch/virtual-dom#286]
Hi Team,

This is a question not an issue. Im moving certain old handlebars code to virtual-dom and I am not sure how to generate any arbitrary attribute. 
For example:
This HTML
```html
<form novalidate> </form>
```
I thought should be generated from this virtual-dom:
```javascript
h('form', {novalidate:''})
```
But in fact the final form does not contain any attribute at all.

I have experimented this behavior when non-standard properties are used, and I know I shouldn’t use stuff like 
```html
<div undocumentendproperty=”value” ></div>
```
Unfortunately my legacy code contain things like this.

Finally, could you please provide any documentation on how data-attributes should be handle. I mean, I know that this properties wont be present in the final dom and that I must use a DataSet object, but apart from that I couldn’t find any example.

Thanks in advance.

**Comment by mtyaka** [comment]
You can set arbitrary attributes using the [`attributes`](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#propertiesattributes) property:

    h('form', {attributes: {novalidate: ''}})

**Comment by Mictian** [comment]
Great, thank you very much! 
:+1:
