### ISSUE TITLE
Create element incorrectly sets `data-*` attributes to properties

### ISSUE THREAD

**Issue by jshthornton** [Matt-Esch/virtual-dom#288]
Create element appears to be setting data attributes directly to the DOM properties and not to the dataset property. This results in being unable to use data attributes.

**Comment by jshthornton** [comment]
This can be fixed in one of two ways.
Either use the `dataset` property (but then will need to fix the html2hscript parser) or when applying properties the data attributes are handled as an dataset object.

**Comment by mtyaka** [comment]
You should use the [`attributes`](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#propertiesattributes) property when setting `data-*` attributes:

    h('div', {attributes: {'data-foo': 'bar'}})

**Comment by jshthornton** [comment]
Agreed. I think I will probably open this issue onto the html2hscript converter, as this is where this issue stems.

**Comment by gajus** [comment]
This should be a FAQ.

**Comment by gajus** [comment]
Just in case anyone stumbles upon this looking for the proper JSX syntax, that is:

```html
<div attributes={{'data-foo': 'bar'}}></div>
```

**Comment by Matt-Esch** [comment]
dataet is really inconsistent across browsers. attributes should always be preferred

**Comment by RangerMauve** [comment]
@gajus Thanks for the tip! Came across this and was a little confused for a moment.
