### ISSUE TITLE
virtual-dom breaks on latest patch

### ISSUE THREAD

**Issue by yoshuawuyts** [Matt-Esch/virtual-dom#292]
[tests for `vel`](https://travis-ci.org/yoshuawuyts/vel) started failing, and users reported [`virtual-dom-starter` no longer works](https://github.com/substack/virtual-dom-starter/issues/4) (confirmed). In both cases it appears that the [patch function](https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/patch.js#L14) hangs on a loop.

I'm not sure what changed: I started notidicing this today. Maybe a dependency somewhere changed? Thanks!

**Comment by yoshuawuyts** [comment]
Just ran all `virtual-dom` tests, found no issues there. Changes are probably in the library then.

**Comment by yoshuawuyts** [comment]
Appears `v2.1.0` fails, `v2.0.1` does not. Probably will need to do a `git bisect` from 3f1d123f0498b73be759b47f3ede32a0e33393e9 onwards.

**Comment by yoshuawuyts** [comment]
Tapping out for the night, will be working mostly offline tomorrow. I hope someone can figure out what's causing the breakage.

**Comment by Raynos** [comment]
Probably https://github.com/Matt-Esch/virtual-dom/commit/519fd8d01844206729c64358f4367be7aac55956

**Comment by substack** [comment]
This bug appears to be fixed now in 2.1.1.
