### ISSUE TITLE
Question: How to create comment nodes

### ISSUE THREAD

**Issue by Mictian** [Matt-Esch/virtual-dom#301]
Hi Team,

This is a question not an issue. I would like to know how, if it is even possible, create comment nodes.
Clearly in not something you want to have in production (loose computation time analyzing diff between comments)  but do make sense during development.

Thank in advance.

**Comment by stevenvachon** [comment]
This might be helpful: https://github.com/lhorie/mithril.js/issues/396

**Comment by Mictian** [comment]
Interesting!
Thanks for pointing that out.
Although I will analyze it, that implies changing from Virtual-DOM to Mithril, which is something that I cannot do right now.

**Comment by stevenvachon** [comment]
@Mictian does this work? `h("!", null, "comment text")`?

**Comment by Mictian** [comment]
Unfortunately Nope

**Comment by MattDeeg** [comment]
Our team uses a [Widget](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md) for comment nodes that you can find [here](https://github.com/wayfair/tungstenjs/blob/unit_test_updates/src/template/widgets/html_comment.js)
Just put `new HTMLCommentWidget(comment)` on your virtual tree like any other node

**Comment by Mictian** [comment]
Thank you very much! It works like charm :smile:  :+1:
