### ISSUE TITLE
Is child combinator selector supported?

### ISSUE THREAD

**Issue by onbjerg** [Matt-Esch/virtual-dom#302]
It does not seem to work, but I do not know if it is intentional or not:

I expected
```js
var tree = h('div > table')
var rootNode = createElement(tree)
el.appendChild(rootNode)
```

to append this HTML to the element in question

```html
<div>
    <table>
    </table>
</div>
```

But it seems like it only adds the div. Why?

**Comment by hawkerboy7** [comment]
Well I am not sure but you can create an (single) element using h(). A div is an element, a table is an element too, so that's probably why that won't work. However I just started with this awesome virtual-dom so I may very well be wrong! :)

**Comment by eightyeight** [comment]
To generate that HTML, you should write:

```js
h('div', h('table'));
```

Or, with properties and more children:

```js
h('div.foo', {attributes: {foo: 'bar'}}, [
  h('table.bar'),
  h('table#baz'),
]);
```

Which gives:

```html
<div class="foo" foo="bar">
   <table class="bar"></table>
   <table id="baz"></table>
</div>
```

The hyperscript shorthand is not literal CSS selector syntax, but uses it to quickly set class and ID names.

**Comment by onbjerg** [comment]
Sure. I just wanted to know if there was a faster way to create child elements. Thanks.
