### ISSUE TITLE
Looking for advice on ordering child thunks?

### ISSUE THREAD

**Issue by rolandpoulter** [Matt-Esch/virtual-dom#303]
I'm trying to write a soft implementation of Reacts component API using virtual-dom. My implementation has a bug that I'm trying to fix where a component with child components that can be added and removed.

I believe the problem I'm having could be side effect of how I've integrated with virtual-dom. I'm using thunks to create component placeholders. A component thunk renders a widget which delegates to a component object.

When the list of child components changes on parent component a new set of thunks are generated. Each given a new component object. Is there a way I could provide some kind of key property to a thunk so that virtual-dom can better determine the previous vnode for a thunk?

In case its helpful here is wip code where my ComponentThunk and ComponentWidget classes are defined: https://github.com/rolandpoulter/mach-react/blob/wip/src/machReact.js#L191

**Comment by Zolmeister** [comment]
Check out [Zorium](https://zorium.org/) (specifically [this file](https://github.com/Zorium/zorium/blob/master/src/z.coffee)) for how we do thunks.

**Comment by rolandpoulter** [comment]
Thanks @Zolmeister this is very helpful. Seems like I should remove my ComponentWidget altogether, and just call the components' render method right away. This would allow me to pass a key to the element. I'll give this a try to see if it fixes the problem I'm having.
