### ISSUE TITLE
support setting attributes

### ISSUE THREAD

**Issue by neonstalwart** [Matt-Esch/virtual-dom#32]
here is one use case for attributes rather than properties...

``` js
f = document.createElement('form');
document.body.appendChild(f);
i = document.createElement('input');
f.appendChild(i);
i.value = 'foo';
f.reset(); // i.value is ''
i.setAttribute('value', 'foo');
i.value = 'bar';
f.reset(); // i.value is 'foo';
```

it should be simple to indicate that you want to use an attribute via the use of `[attribute=value]` in the `tagName` string.

``` js
h('input.check[type=checkbox][data-foo=bar][name=baz]')
```

**Comment by AlexGalays** [comment]
How about svg attributes? It's quite a pain to write.
That reads a bit nicer imo:  http://jsfiddle.net/rcEex/

**Comment by Zolmeister** [comment]
We use this feature extensively https://github.com/claydotio/clay-mobile/blob/master/src/components/home/index.coffee
It is most definitely useful
