### ISSUE TITLE
Create a Vtree from DOM?

### ISSUE THREAD

**Issue by leegee** [Matt-Esch/virtual-dom#337]
Newbie question, sorry if it is dumb, but can a virtual DOM tree be created from a DOM tree, or do I have to roll my own?
Some examples in the dist would be very helpful.

**Comment by hallgren** [comment]
I use `html-to-vdom` and 

```js

var VNode = require('virtual-dom/vnode/vnode');
var VText = require('virtual-dom/vnode/vtext');
var convertHTML = require('html-to-vdom')({
    VNode: VNode,
    VText: VText
});

var element = document.getElementById("elementId")
var vTree = convertHTML(element.outerHTML.trim());
```

Don´t know if it the best way?

**Comment by leegee** [comment]
Thank you very much! Sorry to have missed it if it is obvious.

**Comment by leegee** [comment]
Thank you very much — I did not see the project wiki.
