### ISSUE TITLE
Best way to draw to canvas elements in the VDom.

### ISSUE THREAD

**Issue by naomiaro** [Matt-Esch/virtual-dom#342]
I'm just wondering what is the best approach to this problem with virtual dom + canvas. I don't really see any examples after doing a brief search and wonder if it has been done much before.

**Comment by Zolmeister** [comment]
Hooks - https://github.com/Matt-Esch/virtual-dom/blob/master/docs/hooks.md

**Comment by naomiaro** [comment]
Great thanks! I totally missed seeing the hooks documentation for this project.
