### ISSUE TITLE
virtual-hyperscript number support

### ISSUE THREAD

**Issue by sprat** [Matt-Esch/virtual-dom#344]
`virtual-hyperscript` supports a number as children, converted automatically to a `VText` node:

``` javascript
h('div', {}, 3)
```

But it does not work if we don't pass the properties dict, like this:

``` javascript
h('div', 3)
```

In fact, there's a special case for numbers in `addChild` but I guess we miss the same special case in `isChildren`.

**Comment by kuraga** [comment]
See #297

**Comment by sprat** [comment]
I'm just asking support for `h('div', 3)`, since we can already write `h('div', '3')`. But #297 would be a nice API improvement too in my opinion ;)

**Comment by sprat** [comment]
If I work on a pull request supporting the "number" type, will it be merged?

**Comment by Zolmeister** [comment]
@sprat I think this was fixed - https://github.com/Matt-Esch/virtual-dom/pull/290

**Comment by sprat** [comment]
But looking at the code, I don't think it is fixed: my problem was in `isChildren` not detecting a number as valid child
