### ISSUE TITLE
diff/patch with markdown preview

### ISSUE THREAD

**Issue by whisper-bye** [Matt-Esch/virtual-dom#349]
When I preview huge markdown file with changes, innerHTML is very slow,
can I use virtual-dom to smart innerHTML? I don't know how to do it, thx.

**Comment by Zolmeister** [comment]
https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md

**Comment by hallgren** [comment]
I played around with just this in Krumelur: https://github.com/hallgren/krumelur and compare it with innerHTML here: https://twitter.com/morganhallgren/status/670154114794430465

**Comment by whisper-bye** [comment]
@hallgren nice project, clear API, but in my test, some html tags is wrong, like h1 convert to p, and a little slow

**Comment by hallgren** [comment]
@whisper-bye thanks for trying it out.

Would be interesting to see your test. I just pushed some changes that now uses vdom-parser instead of html-to-vdom to convert html to a vtree. Please try it again if you have the time.

**Comment by whisper-bye** [comment]
@hallgren thank you hallgren, I tried it out, it is faster than before, but the tags still convert to <p>
I just convert 10000 lines markdown statements convert to html from the marked lib, It seems to be virtual-dom's problem.

**Comment by hallgren** [comment]
Aha I see. Krumelur takes a HTML string and update the applied element. It don´t handle the parsing from Markdown to HTML. Sorry I missed the question abit :)

**Comment by whisper-bye** [comment]
@hallgren I tried some others diff/patch library, they have the same problem, they also use the virtual-dom lib...but I do not know where the problem...

**Comment by hallgren** [comment]
I have a test page https://fast-tundra-5509.herokuapp.com/many that includes h1 tags and it seams to work after a diff/patch.
