### ISSUE TITLE
Include stringily algorithm

### ISSUE THREAD

**Issue by calebmer** [Matt-Esch/virtual-dom#351]
Could a virtual dom to html algorithm be included in this module? [Here](https://github.com/nthtran/vdom-to-html/) is one example of an algorithm, and I would be completely willing to write one in this codebase's style.

The argument for this would be that if the module contains a vdom to dom algorithm, it should also contain the symmetrical vdom to html algorithm for server side usage.

If the distributable file size is a blocker (which it should be) then it can just be included in a separate file to be conditionally required and not included in `index.js`. For example `require('virutal-dom/stringify')` would get the algorithm and `require('virtual-dom').stringify` would not.

**Comment by Raynos** [comment]
There are already 5 user land modules that do this. 

See: https://github.com/Matt-Esch/virtual-dom/wiki

**Comment by calebmer** [comment]
If there are 5 modules, isn't that a sign there should be one definitive implementation?

Especially, as I've learned, the goal is to split up this one module into many smaller ones.
