### ISSUE TITLE
onDestroy hooks

### ISSUE THREAD

**Issue by rstacruz** [Matt-Esch/virtual-dom#353]
The hooks API allows you to inspect creations and changes. How about when a node is going to be unmounted?

**Comment by Zolmeister** [comment]
There is a poorly documented `unhook` property you can add, as seen here.

http://stackoverflow.com/questions/30667351/virtual-dom-how-to-get-hold-of-real-dom-element-in-order-to-integrate-with-spi

PR for docs welcome

**Comment by rstacruz** [comment]
Thanks! that does it.
