### ISSUE TITLE
Include new tool?

### ISSUE THREAD

**Issue by LookLikeAPro** [Matt-Esch/virtual-dom#374]
I made [virtual-hyperscript-parser](https://github.com/LookLikeAPro/virtual-hyperscript-parser) because there were no similar tools available. Parsing html to hypersrcipt in run time is a useful feature in my opinion, and the npm module was downloaded 160 times in the past week.

It is worthwhile to include it in the tools section on README?

**Comment by Zolmeister** [comment]
similar to: https://github.com/bitinn/vdom-parser

**Comment by VictorQueiroz** [comment]
Maybe a preprocessing provides more performance if you build each template into a different template file? Check [vdom-raw](https://github.com/VictorQueiroz/vdom-raw) out.

### Nunjucks (dom.template.js)
```js
module.exports = function render() {
  return {{preprocessed_javascript}};
};
```

**Comment by LookLikeAPro** [comment]
@Zolmeister good point
