### ISSUE TITLE
Question: HTML string to vTree

### ISSUE THREAD

**Issue by davidworkman9** [Matt-Esch/virtual-dom#439]
I'm wondering if there's a way I can seed the virtual-dom with a HTML string, without using eval. Below works, using `dom2hscript` to parse an HTML string into a hyperscript string, then eval it with `virtual-dom/h` in global scope, however using eval and polluting the global namespace are two things I'd like to avoid.

```
const lastOutput = eval(dom2hscript.parseHTML(html));
const el = createElement(lastOutput);
```

**Comment by hallgren** [comment]
I use [vdom-parser](https://www.npmjs.com/package/vdom-parser) to parse html strings into Vtree´s in [Krumelur](https://github.com/hallgren/krumelur)

**Comment by davidworkman9** [comment]
@hallgren thanks that's exactly what I was looking for!
