### ISSUE TITLE
properties aren't all added to element.

### ISSUE THREAD

**Issue by BrunoEVCosta** [Matt-Esch/virtual-dom#452]
For example:
```
   { xmlns: 'http://www.w3.org/2000/svg',
     'xmlns:xlink': 'http://www.w3.org/1999/xlink',
     width: '500',
     height: '272.82',
     viewBox: '0,3.574,100,54.564' },

```

viewBox and xmlns properties are lost

**Comment by jamesamcl** [comment]
Use svg rather than h

See https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/test/svg.js for an example.

**Comment by BrunoEVCosta** [comment]
Wow thanks very must this just solved my problem. Not sure if this closes the issue but its a simple fix.
